### ISSUE TITLE
공통 모듈 만들기

### ISSUE THREAD

**Issue by uzhjd** [Don-tOctopus/PlayWithFriend_Server#7]
domain
repository
util
response

**Comment by sudhdkso** [comment]
response에 대한 포맷을 똑같은 형식으로 맞추기 위해서 파일 추가
`
{
    "success": true,
    "code": 200,
    "message": "",
    "data": {
    }
}
`
위와 같은 형식으로 출력 될 수 있도록 변경common>domain>enums>Status.java
출력이 필요한 code와 message는 [common>domain>enums>Status.java](https://github.com/Don-tOctopus/PlayWithFriend_Server/blob/dev/src/main/java/com/octopus/friends/common/domain/enums/Status.java)에 추가하여 사용
